/**
 * design-tokens/compose.cjs — Jetpack Compose (Kotlin) theme emitter +
 * re-extractor (Phase 34.1 Plan 01).
 *
 * Consumes the canonical Phase-23 token map ({ tokens: Record<string,string> })
 * and emits a deterministic Kotlin theme source string: `Color` vals, a
 * `Shapes` block (radius tokens), a `Typography` block (font/text tokens), and
 * a `MaterialTheme` wiring object — per the PRECISION CONTRACT in
 * reference/native-platforms.md.
 *
 * Precision contract:
 *   COLOR      hex -> Color(0xAARRGGBB) long. 8-bit channels EXACT; #RGB
 *              expands; alpha 0xFF when absent.
 *   DIMENSION  Npx -> N.dp (integer dp, round-half-up).
 *   TYPOGRAPHY strings -> Kotlin string literal, pass-through.
 *   NON-MAPPABLE var()/calc()/gradient/rem/em -> verbatim comment, EXCLUDED.
 *
 * Each emitted token line carries a `// token: <original-key>` marker so the
 * symmetric `reextractCompose(source)` recovers the exact canonical key+value.
 * Pure: no fs, no network, no Date, no process.env, no child_process (D-10).
 */

'use strict';

const {
  TOKEN_MARKER,
  NONMAPPABLE_MARKER,
  readTokens,
  sortedEntries,
  classify,
  parseHexChannels,
  channelsToArgbLiteral,
  argbLiteralToChannels,
  channelsToHex,
  pxToInt,
  swiftIdent,
} = require('./_native-shared.cjs');

const RADIUS_RE = /(^|[^a-z])radius/i;

/**
 * Emit a Jetpack Compose / Kotlin theme source string from a token set.
 *
 * @param {{tokens: Record<string,string>}|Record<string,string>} tokenSet
 * @returns {string}
 */
function emitCompose(tokenSet) {
  const tokens = readTokens(tokenSet);
  const entries = sortedEntries(tokens);
  const lines = [];
  lines.push('// Generated by hone — Jetpack Compose theme tokens.');
  lines.push('// See reference/native-platforms.md (token-bridge precision contract).');
  lines.push('import androidx.compose.ui.graphics.Color');
  lines.push('import androidx.compose.ui.unit.dp');
  lines.push('import androidx.compose.material3.Shapes');
  lines.push('import androidx.compose.material3.Typography');
  lines.push('import androidx.compose.foundation.shape.RoundedCornerShape');
  lines.push('');
  lines.push('object GDDTheme {');

  // Colors
  for (const [key, value] of entries) {
    if (classify(key, value) !== 'color') continue;
    const { r, g, b, a, hadAlpha } = parseHexChannels(value);
    lines.push(
      `    val ${swiftIdent(key)} = Color(${channelsToArgbLiteral({ r, g, b, a })}) ${TOKEN_MARKER}${key} hadAlpha=${hadAlpha ? 1 : 0}`,
    );
  }

  // Dimensions (dp)
  for (const [key, value] of entries) {
    if (classify(key, value) !== 'dimension') continue;
    lines.push(
      `    val ${swiftIdent(key)} = ${pxToInt(value)}.dp ${TOKEN_MARKER}${key}`,
    );
  }

  // Typography (strings)
  for (const [key, value] of entries) {
    if (classify(key, value) !== 'typography') continue;
    lines.push(
      `    val ${swiftIdent(key)} = ${JSON.stringify(value)} ${TOKEN_MARKER}${key}`,
    );
  }

  // Non-mappable — verbatim, excluded from identity set
  for (const [key, value] of entries) {
    if (classify(key, value) !== 'non-mappable') continue;
    lines.push(`    ${NONMAPPABLE_MARKER}${key} = ${value}`);
  }

  // Shapes block (from radius dimension tokens) — wires dp into RoundedCornerShape
  lines.push('');
  lines.push('    val Shapes = Shapes(');
  for (const [key, value] of entries) {
    if (classify(key, value) !== 'dimension') continue;
    if (!RADIUS_RE.test(key)) continue;
    lines.push(`        // ${key}: RoundedCornerShape(${pxToInt(value)}.dp)`);
  }
  lines.push('    )');

  // Typography block (MaterialTheme wiring) — references the font tokens above
  lines.push('    val Typography = Typography()');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

const COMPOSE_COLOR_RE = new RegExp(
  String.raw`val \w+ = Color\((0x[0-9a-fA-F]{8})\)\s*` +
    TOKEN_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') +
    String.raw`(\S+)\s+hadAlpha=([01])`,
);
const COMPOSE_DIM_RE = new RegExp(
  String.raw`val \w+ = (\d+)\.dp\s*` +
    TOKEN_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') +
    String.raw`(\S+)`,
);
const COMPOSE_STR_RE = new RegExp(
  String.raw`val \w+ = ("(?:[^"\\]|\\.)*")\s*` +
    TOKEN_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') +
    String.raw`(\S+)`,
);

/**
 * Recover the canonical token map from an emitted Compose source string.
 * Non-mappable lines and the Shapes-comment lines are NOT recovered.
 *
 * @param {string} source
 * @returns {{tokens: Record<string,string>}}
 */
function reextractCompose(source) {
  /** @type {Record<string,string>} */
  const tokens = {};
  for (const line of String(source).split(/\r?\n/)) {
    if (line.includes(NONMAPPABLE_MARKER)) continue;
    let m;
    if ((m = COMPOSE_COLOR_RE.exec(line))) {
      const ch = argbLiteralToChannels(m[1]);
      tokens[m[2]] = channelsToHex(ch.r, ch.g, ch.b, ch.a, m[3] === '1');
    } else if ((m = COMPOSE_DIM_RE.exec(line))) {
      tokens[m[2]] = `${m[1]}px`;
    } else if ((m = COMPOSE_STR_RE.exec(line))) {
      tokens[m[2]] = JSON.parse(m[1]);
    }
  }
  return { tokens };
}

module.exports = { emitCompose, reextractCompose };
