/**
 * design-tokens/flutter.cjs — Flutter (Dart) theme emitter + re-extractor
 * (Phase 34.1 Plan 01).
 *
 * Consumes the canonical Phase-23 token map ({ tokens: Record<string,string> })
 * and emits a deterministic Dart theme source string: a `GDDTheme` constants
 * class plus a `themeData()` builder wiring `ColorScheme` + `TextTheme` into a
 * `ThemeData` — per the PRECISION CONTRACT in reference/native-platforms.md.
 *
 * Precision contract:
 *   COLOR      hex -> Color(0xAARRGGBB). 8-bit channels EXACT; #RGB expands;
 *              alpha 0xFF when absent.
 *   DIMENSION  Npx -> logical-px double (`16` -> `16.0`); NOT rounded.
 *   TYPOGRAPHY strings -> Dart string literal, pass-through.
 *   NON-MAPPABLE var()/calc()/gradient/rem/em -> verbatim comment, EXCLUDED.
 *
 * Each emitted token line carries a `// token: <original-key>` marker so the
 * symmetric `reextractFlutter(source)` recovers the exact canonical key+value.
 * Pure: no fs, no network, no Date, no process.env, no child_process (D-10).
 */

'use strict';

const {
  TOKEN_MARKER,
  NONMAPPABLE_MARKER,
  readTokens,
  sortedEntries,
  classify,
  parseHexChannels,
  channelsToArgbLiteral,
  argbLiteralToChannels,
  channelsToHex,
  pxToDouble,
  swiftIdent,
} = require('./_native-shared.cjs');

/**
 * Emit a Flutter / Dart theme source string from a token set.
 *
 * @param {{tokens: Record<string,string>}|Record<string,string>} tokenSet
 * @returns {string}
 */
function emitFlutter(tokenSet) {
  const tokens = readTokens(tokenSet);
  const entries = sortedEntries(tokens);
  const lines = [];
  lines.push('// Generated by hone — Flutter theme tokens.');
  lines.push('// See reference/native-platforms.md (token-bridge precision contract).');
  lines.push("import 'package:flutter/material.dart';");
  lines.push('');
  lines.push('class GDDTheme {');

  for (const [key, value] of entries) {
    const kind = classify(key, value);
    const ident = swiftIdent(key);
    if (kind === 'color') {
      const { r, g, b, a, hadAlpha } = parseHexChannels(value);
      lines.push(
        `  static const ${ident} = Color(${channelsToArgbLiteral({ r, g, b, a })}); ${TOKEN_MARKER}${key} hadAlpha=${hadAlpha ? 1 : 0}`,
      );
    } else if (kind === 'dimension') {
      lines.push(
        `  static const ${ident} = ${pxToDouble(value)}; ${TOKEN_MARKER}${key}`,
      );
    } else if (kind === 'typography') {
      lines.push(
        `  static const ${ident} = ${JSON.stringify(value)}; ${TOKEN_MARKER}${key}`,
      );
    } else {
      lines.push(`  ${NONMAPPABLE_MARKER}${key} = ${value}`);
    }
  }

  // ThemeData builder wiring ColorScheme + TextTheme (MaterialTheme analog).
  lines.push('');
  lines.push('  static ThemeData themeData() => ThemeData(');
  lines.push('        colorScheme: ColorScheme.fromSeed(seedColor: GDDTheme.colorPrimary),');
  lines.push('        textTheme: const TextTheme(),');
  lines.push('      );');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

const FLUTTER_COLOR_RE = new RegExp(
  String.raw`static const \w+ = Color\((0x[0-9a-fA-F]{8})\);\s*` +
    TOKEN_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') +
    String.raw`(\S+)\s+hadAlpha=([01])`,
);
const FLUTTER_DIM_RE = new RegExp(
  String.raw`static const \w+ = (\d+(?:\.\d+)?);\s*` +
    TOKEN_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') +
    String.raw`(\S+)`,
);
const FLUTTER_STR_RE = new RegExp(
  String.raw`static const \w+ = ("(?:[^"\\]|\\.)*");\s*` +
    TOKEN_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') +
    String.raw`(\S+)`,
);

/**
 * Recover the canonical token map from an emitted Flutter source string.
 * Non-mappable lines + the ThemeData builder lines are NOT recovered.
 *
 * @param {string} source
 * @returns {{tokens: Record<string,string>}}
 */
function reextractFlutter(source) {
  /** @type {Record<string,string>} */
  const tokens = {};
  for (const line of String(source).split(/\r?\n/)) {
    if (line.includes(NONMAPPABLE_MARKER)) continue;
    let m;
    if ((m = FLUTTER_COLOR_RE.exec(line))) {
      const ch = argbLiteralToChannels(m[1]);
      tokens[m[2]] = channelsToHex(ch.r, ch.g, ch.b, ch.a, m[3] === '1');
    } else if ((m = FLUTTER_DIM_RE.exec(line))) {
      // Recover canonical Npx: a logical-px double `16.0` -> `16px`.
      tokens[m[2]] = `${parseFloat(m[1])}px`;
    } else if ((m = FLUTTER_STR_RE.exec(line))) {
      tokens[m[2]] = JSON.parse(m[1]);
    }
  }
  return { tokens };
}

module.exports = { emitFlutter, reextractFlutter };
