/**
 * design-tokens/swift.cjs — SwiftUI theme emitter + re-extractor
 * (Phase 34.1 Plan 01).
 *
 * Consumes the canonical Phase-23 token map ({ tokens: Record<string,string> })
 * and emits a deterministic SwiftUI theme source string: an `enum GDDTheme`
 * exposing static `Color` / `CGFloat` (pt) / `String` constants per the
 * PRECISION CONTRACT in reference/native-platforms.md.
 *
 * Precision contract (the round-trip's definition of "identity preserved"):
 *   COLOR      hex #RGB/#RRGGBB/#RRGGBBAA -> Color(red:G/255 ...). 8-bit
 *              channels EXACT (numerator-over-255 form avoids float drift);
 *              #RGB expands to #RRGGBB; alpha opaque (255) when absent.
 *   DIMENSION  Npx -> CGFloat integer points (round-half-up).
 *   TYPOGRAPHY font-family / strings -> String literal, pass-through.
 *   NON-MAPPABLE var()/calc()/gradient/rem/em -> verbatim trailing comment,
 *              EXCLUDED from the round-trip identity set.
 *
 * Each emitted token line carries a `// token: <original-key>` marker so the
 * symmetric `reextractSwift(source)` recovers the exact canonical key + value.
 * Pure: no fs, no network, no Date, no process.env, no child_process (D-10).
 */

'use strict';

const {
  TOKEN_MARKER,
  NONMAPPABLE_MARKER,
  readTokens,
  sortedEntries,
  classify,
  parseHexChannels,
  channelsToHex,
  pxToInt,
  swiftIdent,
} = require('./_native-shared.cjs');

/**
 * Emit a SwiftUI theme source string from a token set.
 *
 * @param {{tokens: Record<string,string>}|Record<string,string>} tokenSet
 * @returns {string}
 */
function emitSwift(tokenSet) {
  const tokens = readTokens(tokenSet);
  const lines = [];
  lines.push('// Generated by get-design-done — SwiftUI theme tokens.');
  lines.push('// See reference/native-platforms.md (token-bridge precision contract).');
  lines.push('import SwiftUI');
  lines.push('');
  lines.push('enum GDDTheme {');
  for (const [key, value] of sortedEntries(tokens)) {
    const ident = swiftIdent(key);
    const kind = classify(key, value);
    if (kind === 'color') {
      const { r, g, b, a, hadAlpha } = parseHexChannels(value);
      const alphaSlot = hadAlpha
        ? `, opacity: ${a}.0/255.0`
        : `, opacity: 255.0/255.0`;
      lines.push(
        `    static let ${ident} = Color(red: ${r}.0/255.0, green: ${g}.0/255.0, blue: ${b}.0/255.0${alphaSlot}) ${TOKEN_MARKER}${key} hadAlpha=${hadAlpha ? 1 : 0}`,
      );
    } else if (kind === 'dimension') {
      lines.push(
        `    static let ${ident}: CGFloat = ${pxToInt(value)} ${TOKEN_MARKER}${key}`,
      );
    } else if (kind === 'typography') {
      lines.push(
        `    static let ${ident} = ${JSON.stringify(value)} ${TOKEN_MARKER}${key}`,
      );
    } else {
      // non-mappable — verbatim, excluded from identity set
      lines.push(`    ${NONMAPPABLE_MARKER}${key} = ${value}`);
    }
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

const SWIFT_COLOR_RE = new RegExp(
  String.raw`Color\(red:\s*(\d+)\.0/255\.0,\s*green:\s*(\d+)\.0/255\.0,\s*blue:\s*(\d+)\.0/255\.0,\s*opacity:\s*(\d+)\.0/255\.0\)\s*` +
    TOKEN_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') +
    String.raw`(\S+)\s+hadAlpha=([01])`,
);
const SWIFT_DIM_RE = new RegExp(
  String.raw`:\s*CGFloat\s*=\s*(\d+)\s*` +
    TOKEN_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') +
    String.raw`(\S+)`,
);
const SWIFT_STR_RE = new RegExp(
  String.raw`static let \w+ = ("(?:[^"\\]|\\.)*")\s*` +
    TOKEN_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') +
    String.raw`(\S+)`,
);

/**
 * Recover the canonical token map from an emitted SwiftUI source string.
 * Non-mappable lines (NONMAPPABLE_MARKER) are intentionally NOT recovered.
 *
 * @param {string} source
 * @returns {{tokens: Record<string,string>}}
 */
function reextractSwift(source) {
  /** @type {Record<string,string>} */
  const tokens = {};
  for (const line of String(source).split(/\r?\n/)) {
    if (line.includes(NONMAPPABLE_MARKER)) continue;
    let m;
    if ((m = SWIFT_COLOR_RE.exec(line))) {
      const [, r, g, b, a, key, hadAlpha] = m;
      tokens[key] = channelsToHex(+r, +g, +b, +a, hadAlpha === '1');
    } else if ((m = SWIFT_DIM_RE.exec(line))) {
      tokens[m[2]] = `${m[1]}px`;
    } else if ((m = SWIFT_STR_RE.exec(line))) {
      tokens[m[2]] = JSON.parse(m[1]);
    }
  }
  return { tokens };
}

module.exports = { emitSwift, reextractSwift };
