'use strict';
/**
 * draft-writer.cjs — Plan 30-04 D-04 payload-on-disk persister.
 *
 * Writes the assembled issue body to a deterministic path under
 * `.design/issue-drafts/<timestamp>-<fp8>.md` BEFORE any consent prompt
 * is shown. The file persists across decline (D-04: user keeps their
 * work) and is the on-disk source-of-truth that promptConsent re-reads
 * on submit.
 *
 * Pure-ish: only fs + clock + Object.freeze. No env reads (D-03 static
 * test would fail). No spawn, no network.
 *
 * The file content is the assembled markdown body verbatim plus a small
 * provenance header (HTML comments). Edits to the file between write
 * and consent are picked up via the re-read in promptConsent.
 */

const fs = require('node:fs');
const path = require('node:path');

const { DESTINATION_REPO } = require('./destination.cjs');

const DRAFTS_SUBDIR = path.join('.design', 'issue-drafts');

/**
 * @param {Date} [now] — clock injection point for hermetic tests
 * @returns {string} — YYYYMMDDTHHMMSSZ (no separators)
 */
function timestampStamp(now) {
  const d = now instanceof Date ? now : new Date();
  const iso = d.toISOString();
  // 2026-05-20T13:14:15.678Z -> 20260520T131415Z
  return iso
    .replace(/[-:]/g, '')
    .replace(/\.\d{3}/, '');
}

/**
 * Compute the destination path for a draft.
 *
 * @param {{ rootDir?: string, fingerprint: string, now?: Date }} opts
 * @returns {string} — absolute path
 */
function draftPath(opts) {
  const rootDir = (opts && opts.rootDir) || process.cwd();
  const fingerprint = String(opts && opts.fingerprint != null ? opts.fingerprint : '');
  if (fingerprint.length < 8 || !/^[a-f0-9]+$/.test(fingerprint)) {
    throw new Error(
      `draft-writer: fingerprint must be a hex string of length ≥ 8 (got: ${JSON.stringify(fingerprint)})`
    );
  }
  const fp8 = fingerprint.slice(0, 8);
  const stamp = timestampStamp(opts && opts.now);
  return path.join(rootDir, DRAFTS_SUBDIR, `${stamp}-${fp8}.md`);
}

/**
 * Render the markdown that lives on disk.
 *
 * @param {{ title: string, body: string, fingerprint: string, now?: Date }} args
 * @returns {string}
 */
function renderDraft(args) {
  const now = args && args.now instanceof Date ? args.now : new Date();
  const title = String(args && args.title != null ? args.title : '');
  const body = String(args && args.body != null ? args.body : '');
  const fingerprint = String(args && args.fingerprint != null ? args.fingerprint : '');

  return [
    `<!-- generated by /gdd:report-issue at ${now.toISOString()} -->`,
    `<!-- destination: ${DESTINATION_REPO} -->`,
    `<!-- fingerprint: ${fingerprint} -->`,
    `# ${title}`,
    '',
    body,
  ].join('\n');
}

/**
 * Write the draft to disk.
 *
 * Parses the leading `# ...` line and the leading HTML comments off the
 * stored file when promptConsent re-reads it — keeps a simple round-trip
 * shape so users can edit the title by changing the `# ...` line.
 *
 * @param {{
 *   title: string,
 *   body: string,
 *   fingerprint: string,
 *   rootDir?: string,
 *   now?: Date
 * }} args
 * @returns {{ path: string, fingerprint: string, title: string }}
 */
function writeDraft(args) {
  if (args == null || typeof args !== 'object') {
    throw new Error('draft-writer.writeDraft: args object required');
  }
  const title = String(args.title == null ? '' : args.title);
  const body = String(args.body == null ? '' : args.body);
  const fingerprint = String(args.fingerprint == null ? '' : args.fingerprint);
  const rootDir = args.rootDir || process.cwd();
  const now = args.now instanceof Date ? args.now : new Date();

  if (title.length === 0) {
    throw new Error('draft-writer.writeDraft: title is required');
  }
  if (body.length === 0) {
    throw new Error('draft-writer.writeDraft: body is required');
  }

  const full = draftPath({ rootDir, fingerprint, now });
  fs.mkdirSync(path.dirname(full), { recursive: true });
  const content = renderDraft({ title, body, fingerprint, now });
  fs.writeFileSync(full, content, 'utf8');

  return Object.freeze({ path: full, fingerprint, title });
}

/**
 * Re-read a previously-written draft from disk, parsing the on-disk
 * shape back into `{ title, body }`. Used by promptConsent after the
 * editor exits so user edits are picked up.
 *
 * @param {string} filePath
 * @returns {{ title: string, body: string }}
 */
function readDraft(filePath) {
  const raw = fs.readFileSync(filePath, 'utf8');
  const lines = raw.split(/\r?\n/);
  let i = 0;
  // Skip leading HTML comments + blank lines.
  while (i < lines.length && (lines[i].startsWith('<!--') || lines[i].trim() === '')) {
    i++;
  }
  let title = '';
  if (i < lines.length && lines[i].startsWith('# ')) {
    title = lines[i].slice(2).trim();
    i++;
  }
  // Skip a single blank line if present.
  if (i < lines.length && lines[i].trim() === '') {
    i++;
  }
  const body = lines.slice(i).join('\n').replace(/\s+$/, '');
  return { title, body };
}

module.exports = {
  writeDraft,
  readDraft,
  draftPath,
  renderDraft,
  timestampStamp,
  DRAFTS_SUBDIR,
};
